#include <vfs.h>
#include <alloc.h>

void vfs_init() {
    // Initialize the virtual filesystem
    // Create the root directory...
    // Create the /dev directory...
    // Create the /tmp directory...
    // Create a /tmp/kout file...
}